import = [
    "~/.config/alacritty/catppuccin-mocha.toml",
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
opacity = 0.90

[font]
normal = { family = "Iosevka", style = "Medium" }
size = 9

[keyboard]
bindings = [
{ key = "Back", mods = "Control", chars = "\u0017" },
]
