
[font]
size = 9.5

[font.normal]
family = "JetBrains Mono Nerd Font"

[window]
opacity = 0.9

[window.padding]
x = 10
y = 10

[general]
import = ["/home/moonlitgrace/.config/alacritty/catppuccin-mocha.toml"]
