import = [
    "~/.config/alacritty/catppuccin-mocha.toml",
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
opacity = 0.95

[font]
normal = { family = "JetBrainsMonoNerdFont", style = "Regular" }
size = 9
